<div class="etape_inscription">&Eacute;tape 1/3</div>

<div class="selection_rgpd">

    <h2>Politique de protection des données personnelles</h2>

    <p>
        L'ADEME est attachées au respect des règles de protection de la vie privée des utilisateurs de ses sites internet et de ses applications mobiles.
    </p>
    <p>
        Nous nous engageons à n'utiliser les informations communiquées lors de votre inscription à ce site que pour les traitements nécessaires à son fonctionnement et pour réaliser ponctuellement des enquêtes auprès des utilisateurs, nous permettant d'améliorer la pertinence et la qualité des informations traitées et diffusées.
    </p>
    <?php echo $this->form->render(); ?>

</div>